syntax = "proto3";

package tiebalite.frs;

import "recommend.proto";

option java_multiple_files = true;
option java_package = "app.tiebalite.core.network.proto.frs";

message FrsPageResponseLite {
  tiebalite.recommend.ErrorLite error = 1;
  FrsPageResponseDataLite data = 2;
}

message FrsPageResponseDataLite {
  FrsPageForumInfoLite forum = 2;
  FrsPageInfoLite page = 4;
  repeated tiebalite.recommend.UserLite user_list = 17;
  FrsPageDataLite page_data = 126;
}

message FrsPageInfoLite {
  int32 current_page = 3;
  int32 has_more = 6;
}

message FrsPageForumInfoLite {
  int64 id = 1;
  string name = 2;
  int32 is_like = 6;
  int32 user_level = 7;
  string level_name = 8;
  int32 member_num = 9;
  int32 thread_num = 10;
  int32 post_num = 11;
  int32 cur_score = 13;
  int32 levelup_score = 14;
  FrsPageSignInfoLite sign_in_info = 15;
  string avatar = 24;
  string slogan = 25;
}

message FrsPageSignInfoLite {
  FrsPageSignUserLite user_info = 1;
}

message FrsPageSignUserLite {
  int32 is_sign_in = 2;
  int32 cont_sign_num = 5;
}

message FrsPageDataLite {
  repeated FrsLayoutLite feed_list = 2;
}

message FrsLayoutLite {
  string layout = 1;
  FrsFeedLite feed = 2;
}

message FrsFeedLite {
  repeated FrsComponentLite components = 1;
  string schema = 2;
  repeated FrsKeyValueLite business_info = 5;
  repeated FrsKeyValueLite log_param = 7;
}

message FrsComponentLite {
  string component = 1;
  FrsTextGroupLite feed_title = 3;
  FrsTextGroupLite feed_abstract = 4;
  FrsPicGroupLite feed_pic = 7;
  FrsSocialLite feed_social = 8;
}

message FrsTextGroupLite {
  repeated FrsTextResourceLite data = 1;
}

message FrsTextResourceLite {
  FrsTextLite text_info = 8;
}

message FrsTextLite {
  string text = 1;
}

message FrsPicGroupLite {
  repeated FrsPicLite pics = 1;
}

message FrsPicLite {
  string small_pic_url = 1;
  string big_pic_url = 2;
  string origin_pic_url = 3;
  uint32 width = 4;
  uint32 height = 5;
}

message FrsSocialLite {
  FrsAgreeLite agree = 1;
  int32 comment_num = 2;
  int32 share_num = 3;
  uint64 tid = 4;
}

message FrsAgreeLite {
  int64 agree_num = 1;
}

message FrsKeyValueLite {
  string key = 1;
  string value = 2;
}
