syntax = "proto3";

package tiebalite.frs;

import "feed.proto";
import "recommend.proto";

option java_multiple_files = true;
option java_package = "app.tiebalite.core.network.proto.frs";

message FrsPageResponseLite {
  tiebalite.recommend.ErrorLite error = 1;
  FrsPageResponseDataLite data = 2;
}

message FrsPageResponseDataLite {
  FrsPageForumInfoLite forum = 2;
  FrsPageInfoLite page = 4;
  repeated tiebalite.recommend.UserLite user_list = 17;
  FrsPageDataLite page_data = 126;
}

message FrsPageInfoLite {
  int32 current_page = 3;
  int32 has_more = 6;
}

message FrsPageForumInfoLite {
  int64 id = 1;
  string name = 2;
  int32 is_like = 6;
  int32 user_level = 7;
  string level_name = 8;
  int32 member_num = 9;
  int32 thread_num = 10;
  int32 post_num = 11;
  int32 cur_score = 13;
  int32 levelup_score = 14;
  FrsPageSignInfoLite sign_in_info = 15;
  string avatar = 24;
  string slogan = 25;
}

message FrsPageSignInfoLite {
  FrsPageSignUserLite user_info = 1;
}

message FrsPageSignUserLite {
  int32 is_sign_in = 2;
  int32 cont_sign_num = 5;
}

message FrsPageDataLite {
  repeated tiebalite.feed.FeedLayoutLite feed_list = 2;
}
