syntax = "proto3";

package tiebalite.recommend;

option java_multiple_files = true;
option java_package = "app.tiebalite.core.network.proto.recommend";

message PersonalizedResponseLite {
  ErrorLite error = 1;
  PersonalizedResponseDataLite data = 2;
}

message ErrorLite {
  int32 errorno = 1;
  string errmsg = 2;
  string usermsg = 3;
}

message PersonalizedResponseDataLite {
  repeated ThreadInfoLite thread_list = 2;
}

message ThreadInfoLite {
  int64 id = 1;
  int64 tid = 2;
  string title = 3;
  int32 reply_num = 4;
  int32 last_time_int = 7;
  int32 is_top = 9;
  UserLite author = 18;
  repeated AbstractLite abstract_items = 21;
  repeated MediaLite media = 22;
  string fname = 28;
  int32 create_time = 45;
  int64 author_id = 56;
  int32 agree_num = 124;
  int64 share_num = 135;
  SimpleForumLite forum_info = 155;
}

message UserLite {
  int64 id = 2;
  string name = 3;
  string name_show = 4;
  string portrait = 5;
}

message AbstractLite {
  string text = 2;
}

message MediaLite {
  string big_pic = 3;
  string src_pic = 8;
  uint32 width = 10;
  uint32 height = 11;
  string origin_pic = 15;
}

message SimpleForumLite {
  string name = 2;
  string avatar = 4;
}
