syntax = "proto3";

package tiebalite.recommend;

import "feed.proto";

option java_multiple_files = true;
option java_package = "app.tiebalite.core.network.proto.recommend";

message PersonalizedResponseLite {
  ErrorLite error = 1;
  PersonalizedResponseDataLite data = 2;
}

message ErrorLite {
  int32 errorno = 1;
  string errmsg = 2;
  string usermsg = 3;
}

message PersonalizedResponseDataLite {
  repeated ThreadInfoLite thread_list = 2;
  PersonalizedPageDataLite page_data = 27;
}

message PersonalizedPageDataLite {
  repeated tiebalite.feed.FeedLayoutLite feed_list = 1;
}

message ThreadInfoLite {
  int64 id = 1;
  int64 tid = 2;
  UserLite author = 18;
}

message UserLite {
  int64 id = 2;
  string name = 3;
  string name_show = 4;
  string portrait = 5;
}
