syntax = "proto3";

package tiebalite.thread;

import "agree.proto";

option java_multiple_files = true;
option java_package = "app.tiebalite.core.network.proto.thread";

message PbListResponseLite {
  ThreadErrorLite error = 1;
  PbListResponseDataLite data = 2;
}

message ThreadErrorLite {
  int32 errorno = 1;
  string errmsg = 2;
  string usermsg = 3;
}

message PbListResponseDataLite {
  ThreadInfoLite thread = 1;
  ThreadSimpleForumLite forum = 2;
  repeated ThreadUserLite user_list = 5;
  ThreadPostLite first_floor = 6;
  repeated ThreadPostLite post_list = 7;
  ThreadPageInfoLite page = 8;
}

message ThreadSimpleForumLite {
  int64 id = 1;
  string name = 2;
  string avatar = 4;
}

message ThreadPageInfoLite {
  int32 current_page = 3;
  int32 total_count = 4;
  int32 total_page = 5;
  int32 has_more = 6;
  int32 has_prev = 7;
}

message ThreadInfoLite {
  int64 id = 1;
  string title = 3;
  ThreadUserLite author = 18;
  string fname = 28;
  int64 author_id = 56;
  int32 agree_num = 124;
  AgreeLite agree = 126;
}

message ThreadPostLite {
  uint64 id = 1;
  uint32 floor = 3;
  uint32 time = 4;
  repeated ThreadPbContentLite content = 5;
  uint32 sub_post_number = 13;
  bytes sub_post_list = 15;
  int64 author_id = 19;
  ThreadUserLite author = 23;
  AgreeLite agree = 37;
  int64 tid = 46;
}

message ThreadPbContentLite {
  uint32 type = 1;
  string text = 2;
  string link = 3;
  string src = 4;
  string bsize = 5;
  string cdn_src = 8;
  string big_cdn_src = 9;
  string c = 11;
  string voice_md5 = 12;
  uint32 during_time = 13;
  int64 uid = 15;
  string origin_src = 25;
}

message ThreadUserLite {
  int64 id = 2;
  string name = 3;
  string name_show = 4;
  string portrait = 5;
  int32 level_id = 23;
  string ip_address = 127;
}

message ThreadInlineSubPostsLite {
  uint64 pid = 1;
  repeated ThreadSubPostListLite sub_post_list = 2;
}

message PbFloorResponseLite {
  ThreadErrorLite error = 1;
  PbFloorResponseDataLite data = 2;
}

message PbFloorResponseDataLite {
  ThreadPageInfoLite page = 1;
  ThreadPostLite post = 3;
  repeated ThreadSubPostListLite subpost_list = 4;
  ThreadInfoLite thread = 5;
  ThreadSimpleForumLite forum = 6;
}

message ThreadSubPostListLite {
  uint64 id = 1;
  repeated ThreadPbContentLite content = 2;
  uint32 time = 3;
  int64 author_id = 4;
  uint32 floor = 6;
  ThreadUserLite author = 7;
  AgreeLite agree = 9;
}
